# Generated by Django 3.1.1 on 2021-03-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210314_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Doberman', 'Doberman'), ('Stay_dog', 'Stray dog'), ('German_shepherd', 'German Shepherd'), ('American_bully', 'American bully'), ('Pitbull', 'Pitbull'), ('Golden_retriever', 'Golden retriever')], default='Doberman', max_length=50),
        ),
    ]
