# Generated by Django 3.1.1 on 2021-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210315_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Doberman', 'Doberman'), ('Stay_Dog', 'Stray dog'), ('German_Shepherd', 'German Shepherd'), ('American_Bully', 'American bully'), ('Pitbull', 'Pitbull'), ('Golden_Retriever', 'Golden retriever'), ('Labrador_Retriever', 'Labrador Retriever'), ('French_Bulldog', 'French Bulldog'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Yorkshire_Terrier', 'Yorkshire Terrier'), ('Pitbull', 'Pitbull'), ('Pitbull', 'Pitbull'), ('Pitbull', 'Pitbull')], default='Doberman', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='+91', max_length=13),
        ),
    ]
