# Generated by Django 3.1.1 on 2021-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210315_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Doberman', 'Doberman'), ('Stay Dog', 'Stray dog'), ('German Shepherd', 'German Shepherd'), ('American Bully', 'American bully'), ('Pitbull', 'Pitbull'), ('Golden Retriever', 'Golden retriever'), ('Labrador_Retriever', 'Labrador Retriever'), ('French Bulldog', 'French Bulldog'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Yorkshire_Terrier', 'Yorkshire Terrier')], default='Doberman', max_length=50),
        ),
    ]
