# Generated by Django 3.1.1 on 2021-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210327_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Doberman', 'Doberman'), ('Stay_Dog', 'Stay_Dog'), ('German Shepherd', 'German Shepherd'), ('American_Bully', 'American_Bully'), ('Pitbull', 'Pitbull'), ('Golden Retriever', 'Golden retriever'), ('Labrador_Retriever', 'Labrador Retriever'), ('French Bulldog', 'French Bulldog'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Yorkshire_Terrier', 'Yorkshire Terrier')], default='Doberman', max_length=50),
        ),
    ]
