# Generated by Django 3.1.1 on 2021-03-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210327_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Doberman', 'Doberman'), ('Pitbull', 'Pitbull'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Yorkshire_Terrier', 'Yorkshire Terrier'), ('Stray_Dog', 'Stray Dog')], default='Doberman', max_length=50),
        ),
    ]
