# Generated by Django 3.1.1 on 2021-03-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210327_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
