# Generated by Django 3.1.1 on 2021-04-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Request',
        ),
    ]
