# Generated by Django 3.1.1 on 2021-04-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210401_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
