# Generated by Django 3.1.1 on 2021-04-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210406_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
