# Generated by Django 3.1.1 on 2021-04-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
