# Generated by Django 3.1.1 on 2021-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210409_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AB', 'American Bully'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('DM', 'Doberman'), ('BX', 'Boxer'), ('CC', 'chow chow'), ('GR', 'Golden Retriver'), ('GD', 'Great Dane'), ('LR', 'Labrador retriever'), ('MT', 'Mastiff'), ('PB', 'Pitbull'), ('PR', 'Pomeranian'), ('Poodle', 'Poodle'), ('PG', 'Pug'), ('Rottweiler', 'Rottweiler'), ('SB', 'Saint Bernard'), ('Stray_Dog', 'Stray Dog'), ('ST', 'Shih Tzu'), ('HK', 'Husky'), ('TT', 'Tibetan terrierle'), ('Yorkshire Terrier', 'Yorkshire Terrier'), ('other', 'Other')], max_length=50),
        ),
    ]
