# Generated by Django 3.2 on 2021-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_product_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
