# Generated by Django 3.2 on 2021-05-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_product_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Dog',
        ),
    ]
